/**
 * @slide-machine/shared — single source of truth for data-model types,
 * API DTOs, and AI-provider interfaces shared by client and server
 * (SPEC TECH-6). Exported as TypeScript source; consumers transpile it.
 */
export * from './types/locale'
export * from './types/plans'
export * from './types/user'
export * from './types/project'
export * from './types/template'
export * from './types/layout-trees'
export * from './types/slot-pairing'
export * from './types/text-styles'
export * from './types/text-ink'
export * from './types/slot-limits'
export * from './types/voice-commands'
export * from './types/deck'
export * from './types/tts-voices'
export * from './types/quiz'
export * from './types/export'
export * from './types/social'
export * from './types/actor-channel'
export * from './dto/health'
export * from './dto/config'
export * from './dto/auth'
export * from './dto/feedback'
export * from './dto/profile'
export * from './dto/actions'
export * from './dto/usage'
export * from './dto/billing'
export * from './dto/cost'
export * from './dto/admin-log'
export * from './dto/admin-usage'
export * from './dto/admin-plan'
export * from './dto/admin-settings'
export * from './dto/settings-log'
export * from './dto/generation'
export * from './dto/telemetry'
export * from './dto/images'
export * from './providers/capability'
export * from './providers/transcription'
export * from './providers/diarization'
export * from './providers/generation'
export * from './providers/quiz-generation'
export * from './providers/image-generation'
export * from './providers/tts'
export * from './providers/translation'
export * from './billing/provider'
export * from './lib/drawing-anchor'
export * from './lib/slide-translation'
export * from './lib/tts-language'
export * from './lib/phrase-segment'
export * from './lib/cosine'
export * from './lib/table-tracks'
